### ISSUE TITLE
Service Account Permissions

### ISSUE THREAD

**Issue by uatec** [google-cloud-tools/grafana-gsuite-sync#2]
Before I dive in to this issue I would like to say: Thanks for building this really useful tool. It's small succinct and appears to be exactly what I'm looking for it I could just get beyond this hurdle.

---

Now my hurdle...

There is no documentation here (or anywhere else) about which permissions are required, or how to set up a service account that can be used when running this tool.

I have been trying to work out the correct workflow and permissions, but without success.

This is what I have got so far:

1. Create Service Account with Project View permission
    - Open the [Service accounts page](https://console.developers.google.com/iam-admin/serviceaccounts), If prompted, select a project.
    - Click *Create service account*
    - In the *Create service account* window, type a name for the service account and click *Create*
    - Add the *Project > Viewer* role and click *Continue*
    - Click *Create Key*, select Key type *JSON* and click *Create* to download the key
    - This is the google credentials file to be passed to grafana-gsuite-sync.
2. Enable G Suite Domain-wide Delegation
    - Open the [Service accounts page](https://console.developers.google.com/iam-admin/serviceaccounts), If prompted, select a project.
    - Click the newly created service account
    - Click *Edit*
    - Expand the *Show Domain-Wide Delegation* section.
    - Check the * Enable G Suite Domain-wide Delegation* checkbox
    - Click *Save*
    - Copy the *Client ID* to grant API client access over your domain
3. Grant API client access
    - Go to your G Suite domain's [Admin Console](http://admin.google.com/)
    - Select *Security* from the list of controls. If you don't see *Security* listed, select *More controls* from the grey bar at the bottom of the page, then select *Security* from the list of controls.
    - Select *Advanced settings* from the list of options.
    - Select *Manage API client access* from the *Authentication* section.
    - In the *Client name* field enter the service account's *Client ID*.
    - In the *One or More API Scopes* field enter the list of scopes that your application should be granted access to (see image below). For example if you need domain-wide access to Users and Groups enter: `https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.group`
    - Click the *Authorize* button.

When running this tool after following this process I get this error:
```
[2019-01-23T17:16:52.621Z] ERROR (49472 on EmergencyBacon.local): Not Authorized to access this resource/api
    Error: Not Authorized to access this resource/api
        at createError (/Users/uatec/Development/google-cloud-tools/grafana-gsuite-sync/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/Users/uatec/Development/google-cloud-tools/grafana-gsuite-sync/node_modules/axios/lib/core/settle.js:18:12)
        at Unzip.handleStreamEnd (/Users/uatec/Development/google-cloud-tools/grafana-gsuite-sync/node_modules/axios/lib/adapters/http.js:201:11)
        at Unzip.emit (events.js:187:15)
        at endReadableNT (_stream_readable.js:1094:12)
        at process._tickCallback (internal/process/next_tick.js:63:19)
```

If you can give me a few pointers I can raise a PR to document this process.

**Comment by yacut** [comment]
Sorry for the long delay...

I think the problem is not the google cloud service account permissions, but the permissions for the grafana user account that you're using (`--grafana-username` and `--grafana-password` flags). The grafana user should have the server admin permissions in order to execute grafana api requests.

**Comment by uatec** [comment]
Thanks for getting back to me.

I have confirmed that the Grafana permissions are working correctly. I have extended my PR (https://github.com/google-cloud-tools/grafana-gsuite-sync/pull/1) with logging specifically around the Grafana API calls and Google API calls.

This logging confirmed that:

a) Grafana Organisation was successfully retrieved
b) Grafana users were successfully retrieved

I also notice that the stack trace on the error includes Axios which (after looking through the google API code) is the HTTP client library that the google API uses.

**Comment by yacut** [comment]
Interesting...

did you set the `--google-admin-email` flag? 
It should be a "subject" for the api calls: https://github.com/google-cloud-tools/grafana-gsuite-sync/blob/e4cae5e71d4e9ee5db88f7b6dca89dbc64c94f2b/index.ts#L82

You can find more info about it here: https://developers.google.com/admin-sdk/directory/v1/guides/delegation

**Comment by uatec** [comment]
I see. I must have made the assumption that that was implied with the credentials file.

Presumably this is not the email address of the service account. Given that I am accessing all the directory information, I don't know what email address would be appropriate. Would it be *my* email address?

**Comment by rikimaru0345** [comment]
@uatec 
It would be the email address of an administrator (or anyone who has the right permissions to see *all* groups)

Some people create a new google user in gsuite that is used exclusively as a "target" by service accounts, but that is actually not neccesary at all.
In order for a service account to impersonate someone, that user must explicitly specify what permissions (scopes) the service account can use in their name. This [is actually done in gsuite](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account) instead of the cloud IAM page.

Also, the new tool to use would be:
https://github.com/cloudworkz/grafana-permission-sync
